server:
  port: 8092

spring:
  application:
    name: fraud
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/fraud
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8093/eureka